version: "3"
services:
  mongo:
    image: mongo:3.6-jessie
    container_name: mongo
    networks:
      - backend
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - db-conf:/data/configdb

  bom:
    image: szaffarano/brew-o-matic
    container_name: bom
    ports:
      - 80:3000
    networks:
      - frontend
      - backend
    links:
      - mongo:mongodb
    depends_on:
      - mongo
    volumes:
      - /tmp/config.js:/usr/src/app/config.js

networks:
  frontend:
  backend:

volumes:
  db-data:
  db-conf:
