export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const USER_SETTINGS = "USER_SETTINGS"
export const USER_SETTINGS_METADATA = "USER_SETTINGS_METADATA"
export const APP_STATUS = "APP_STATUS"
export const CLEAR_APP_STATUS = "CLEAR_APP_STATUS"

export const DATA_BOTTLES = "DATA_BOTTLES"
export const DATA_GRAINS = "DATA_GRAINS"
export const DATA_HOPS = "DATA_HOPS"
export const DATA_MISCS = "DATA_MISCS"
export const DATA_STYLES = "DATA_STYLES"
export const DATA_YEASTS = "DATA_YEASTS"
